# Site settings
title:          "Types & Times"
description:    "Programming languages, types, time, and calendars"
#baseurl:        "/"
url:            "https://typesandtimes.net/"

# Author
author:
  name:         Scott Kilpatrick
  url:          
  email:        typesandtimes@gmail.com
  twitter:      "@typesandtimes"

# Build settings
markdown:       kramdown
highlighter:    rouge
kramdown:
  input:              GFM
  hard_wrap:          false
  syntax_highlighter: rouge
  extensions:         fenced_code_blocks

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:month/:title
paginate:       5

google_analytics: UA-132848114-1