# Site settings
title:          Types and Times
description:    "Programming languages, types, calendars, and time zones"
baseurl:        "/"
url:            "https://typesandtimes.github.io"

# Author
author:
  name:         Scott Kilpatrick
  url:          
  email:        skilpat@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
